import { spawn } from 'child_process';
import { join, resolve } from 'path';
import { mkdir, writeFile } from 'fs/promises';

/**
 * Baseline-drift gate (ADR 0008).
 *
 * One-shot, offline, human-run flow for adopting migration history onto an
 * existing database WITHOUT resetting it:
 *   1. verifyNoDrift(dbUrl)  → live DB must exactly match schema.prisma
 *   2. generateBaseline()    → full CREATE script for an empty→schema baseline
 *   3. (human) prisma migrate resolve --applied <name> on the existing DB
 *
 * Deliberately separate from `bootstrapDatabase`: baseline is one-shot offline,
 * bootstrap runs per container start.
 *
 * Drift contract: empty diff output = no drift; non-empty = drift; command
 * failure = hard error, explicitly NOT drift ("drifted" vs "unreachable" are
 * never collapsed into one result).
 */

export interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}

/** Thin seam over process spawning so tests can inject a fake CLI. */
export type RunCommand = (args: string[]) => Promise<RunResult>;

export type DriftStatus = 'clean' | 'drift' | 'error';

export interface DriftReport {
  status: DriftStatus;
  diff?: string;
  error?: string;
}

export interface BaselineFiles {
  migrationSqlPath: string;
  lockFilePath: string;
  migrationName: string;
}

const SCHEMA_DATAMODEL = 'prisma/schema.prisma';
const INIT_MIGRATION = '0_init';

/** Default baseline output root (overridable for tests / custom layouts). */
export const defaultMigrationsRoot = () => resolve('prisma/migrations');

/** Real adapter: spawns the Prisma CLI's `migrate diff` and captures output. */
export function prismaRun(cmd?: string): RunCommand {
  // Run Prisma via `node node_modules/prisma/build/index.js` — works on both
  // Windows and Linux without shell/.cmd launchers.
  const resolvedCmd = cmd ?? process.execPath;
  const prefixArgs = cmd ? [] : ['node_modules/prisma/build/index.js'];
  return (args: string[]) =>
    new Promise<RunResult>((resolvePromise) => {
      const child = spawn(resolvedCmd, [...prefixArgs, ...args], {
        stdio: ['ignore', 'pipe', 'pipe'],
      });
      const stdout: string[] = [];
      const stderr: string[] = [];
      child.stdout.on('data', (d) => stdout.push(d.toString('utf8')));
      child.stderr.on('data', (d) => stderr.push(d.toString('utf8')));
      child.on('error', (err) => {
        resolvePromise({ code: 1, stdout: '', stderr: err.message });
      });
      child.on('close', (code) => {
        resolvePromise({ code: code ?? 1, stdout: stdout.join(''), stderr: stderr.join('') });
      });
    });
}

const diffFromUrl = (dbUrl: string, script: boolean): string[] => [
  'migrate',
  'diff',
  '--from-url',
  dbUrl,
  '--to-schema-datamodel',
  SCHEMA_DATAMODEL,
  ...(script ? ['--script'] : []),
];

const diffFromEmpty = (): string[] => [
  'migrate',
  'diff',
  '--from-empty',
  '--to-schema-datamodel',
  SCHEMA_DATAMODEL,
  '--script',
];

/* Prisma `migrate diff --script` emits this exact comment when there is NO
 * actual schema difference — even though stdout is not empty. It must be
 * treated as "no drift" (only stripped, never a signal on its own). */
const EMPTY_MIGRATION_COMMENT = '-- This is an empty migration.';

export async function verifyNoDrift(
  dbUrl: string,
  run: RunCommand = prismaRun(),
): Promise<DriftReport> {
  let result: RunResult;
  try {
    result = await run(diffFromUrl(dbUrl, true));
  } catch (err) {
    return { status: 'error', error: (err as Error).message };
  }
  if (result.code !== 0) {
    return { status: 'error', error: result.stderr.trim() || `migrate diff exited with code ${result.code}` };
  }
  // Drop the harmless empty-migration comment, then check for real drift.
  const meaningful = result.stdout
    .split('\n')
    .filter((line) => line.trim() !== EMPTY_MIGRATION_COMMENT)
    .join('\n')
    .trim();
  if (meaningful.length === 0) {
    return { status: 'clean' };
  }
  return { status: 'drift', diff: meaningful };
}

export async function generateBaseline(
  run: RunCommand = prismaRun(),
  migrationsRoot: string = defaultMigrationsRoot(),
): Promise<BaselineFiles> {
  const result = await run(diffFromEmpty());
  if (result.code !== 0) {
    throw new Error(result.stderr.trim() || `migrate diff exited with code ${result.code}`);
  }
  const migrationName = INIT_MIGRATION;
  const dir = join(migrationsRoot, migrationName);
  const migrationSqlPath = join(dir, 'migration.sql');
  const lockFilePath = join(dir, 'migration.lock');

  await mkdir(dir, { recursive: true });
  await writeFile(migrationSqlPath, result.stdout, 'utf8');

  // Lock content mirrors what the Prisma CLI writes for a Postgres baseline.
  const lockContent = [
    '# Please do not edit this file manually',
    '# It should be added in your version-control system (i.e. Git)',
    'provider = "postgresql"',
    '',
  ].join('\n');
  await writeFile(lockFilePath, lockContent, 'utf8');

  return { migrationSqlPath, lockFilePath, migrationName };
}

/** CLI entry: `pnpm prisma:migrate:baseline` (ts-node). Never auto-applies. */
export async function main(): Promise<void> {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) {
    throw new Error('DATABASE_URL is required to run the baseline flow.');
  }

  const drift = await verifyNoDrift(dbUrl);
  if (drift.status === 'error') {
    throw new Error(`Drift verification failed (NOT drift): ${drift.error}`);
  }
  if (drift.status === 'drift') {
    throw new Error(`Live DB differs from schema.prisma — baseline aborted.\nDiff:\n${drift.diff}`);
  }

  const baseline = await generateBaseline();
  // eslint-disable-next-line no-console
  console.log(
    [
      'Baseline generated (no drift detected):',
      `  ${baseline.migrationSqlPath}`,
      `  ${baseline.lockFilePath}`,
      '',
      `To mark an existing (already-seeded) DB as having applied this migration, run:`,
      `  prisma migrate resolve --applied ${baseline.migrationName}`,
    ].join('\n'),
  );
}

// CLI entry: ts-node runs this file, `require.main === module` guard keeps it
// inert when imported from unit tests.
if (require.main === module) {
  main().catch((err) => {
    // eslint-disable-next-line no-console
    console.error(`baseline: ${(err as Error).message}`);
    process.exitCode = 1;
  });
}